-- Menu Items Table
create table if not exists menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null,
  category text not null, -- 'Starters', 'Mains', 'Drinks', etc.
  image_url text,
  is_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Reservations Table
create table if not exists reservations (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  reservation_date date not null,
  reservation_time time not null,
  guests integer not null,
  status text default 'pending', -- 'pending', 'confirmed', 'cancelled'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
